# Generated by Django 3.1.7 on 2021-04-24 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.UUIDField()),
                ('height', models.CharField(default='', max_length=50)),
                ('race', models.CharField(default='', max_length=20)),
                ('gender', models.CharField(default='', max_length=10)),
                ('birth', models.CharField(default='', max_length=50)),
                ('spouse', models.CharField(default='', max_length=100)),
                ('death', models.CharField(default='', max_length=20)),
                ('realm', models.CharField(default='', max_length=50)),
                ('hair', models.CharField(default='', max_length=20)),
                ('name', models.CharField(default='', max_length=20)),
                ('url', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.UUIDField()),
                ('dialog', models.CharField(default='', max_length=250)),
                ('movie', models.UUIDField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.character')),
            ],
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characters', models.ManyToManyField(to='app.Character')),
                ('quotes', models.ManyToManyField(to='app.Quote')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
