# Generated by Django 3.1.7 on 2021-04-24 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='url',
            new_name='wikiUrl',
        ),
    ]
