# Generated by Django 3.1.7 on 2021-04-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210424_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='character',
            field=models.CharField(max_length=100),
        ),
    ]
